spring.application.name=beatunes-dbviewer
spring.datasource.url=jdbc:h2:~/Developer/beatunes-dbviewer/beaTunes-F17A2D52DA187A20
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
